#include "nam_core.h"

#include "NAM/dsp.cpp"
#include "NAM/activations.cpp"
#include "NAM/convnet.cpp"
#include "NAM/lstm.cpp"
#include "NAM/util.cpp"
#include "NAM/version.cpp"
#include "NAM/wavenet.cpp"
#include "NAM/get_dsp.cpp"